### ISSUE TITLE
Exception Undefined index: id for configuration

### ISSUE THREAD

**Issue by cve** [mageplaza/magento-2-product-slider#23]
### Preconditions

1. Magento: 2.1.9
2. PHP: 7.0
3. MySQL: 5.6

### Steps to reproduce

1. composer require mageplaza/magento-2-product-slider
2. php bin/magento setup:upgrade
3. php bin/magento setup:static-content:deploy
4. Magento Admin -> Content -> Product Sliders [Configuration]

### Expected result

1. Configuration page

### Actual result

1 exception(s):

```
Exception #0 (Exception): Notice: Undefined index: id in /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 59

Exception #0 (Exception): Notice: Undefined index: id in /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 59
#0 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php(59): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/home/rafjak2/d...', 59, Array)
#1 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/module-config/Model/Config/Structure.php(92): Magento\Config\Model\Config\Structure\Element\Iterator->setElements(Array, 'default')
#2 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/module-config/Block/System/Config/Tabs.php(75): Magento\Config\Model\Config\Structure->getTabs()
#3 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Magento\Config\Block\System\Config\Tabs->__construct(Object(Magento\Backend\Block\Template\Context), Object(Magento\Config\Model\Config\Structure\Interceptor), Object(Magento\Backend\Helper\Data), Array)
#4 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Config\\...', Array)
#5 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Config\\...', Array)
#6 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/View/Element/BlockFactory.php(45): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Config\\...', Array)
#7 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/View/Layout/Generator/Block.php(257): Magento\Framework\View\Element\BlockFactory->createBlock('Magento\\Config\\...', Array)
#8 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/View/Layout/Generator/Block.php(237): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('Magento\\Config\\...', Array)
#9 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/View/Layout/Generator/Block.php(215): Magento\Framework\View\Layout\Generator\Block->createBlock('Magento\\Config\\...', 'adminhtml.syste...', Array)
#10 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/View/Layout/Generator/Block.php(124): Magento\Framework\View\Layout\Generator\Block->generateBlock(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Data\Structure), 'adminhtml.syste...')
#11 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#12 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#13 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#14 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#15 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#16 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#17 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#18 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#19 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#20 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#21 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/module-config/Controller/Adminhtml/System/Config/Edit.php(55): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Config:...')
#22 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/App/Action/Action.php(102): Magento\Config\Controller\Adminhtml\System\Config\Edit->execute()
#23 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/module-config/Controller/Adminhtml/System/AbstractConfig.php(59): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Config\Controller\Adminhtml\System\AbstractConfig->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->___callParent('dispatch', Array)
#27 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Config\\...', 'dispatch', Object(Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor), Array, 'adminAuthentica...')
#28 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#29 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#30 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Config\\...', 'dispatch', Object(Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor), Array, 'adminMassaction...')
#31 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#32 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#33 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/var/generation/Magento/Config/Controller/Adminhtml/System/Config/Edit/Interceptor.php(26): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#34 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/App/FrontController.php(55): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#35 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#36 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#37 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#38 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#39 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#40 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#41 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#42 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#43 /home/rafjak2/domains/rafjak2.ayz.pl/public_html/magento/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#44 {main}
```

**Comment by Kenny1994** [comment]
Hi, 
I'm Kenny from Mageplaza.
Regarding your reported problem, please download and upgrade the Mageplaza_Core module from GitHub: https://github.com/mageplaza/module-core.
In the other hand, if it still doesn't work, please submit your ticket to https://mageplaza.freshdesk.com and provide the following information in the submit form:

- Magento temporary login details (including Back-end URL)
- Temporary SSH/ SFTP log in details (should be able to read/write pub/ var/ folders)
- Order ID

We will look into your particular case as soon as possible.
Thank you very much!

**Comment by suman2061** [comment]
You got the solution? i am also facing same issue
